Rewrite setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,34 +1,61 @@
-#!/usr/bin/env ruby
-require 'pathname'
-require 'fileutils'
-include FileUtils
+#!/bin/sh
 
-# path to your application root.
-APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)
+# Exit if any subcommand fails
+set -e
 
-def system!(*args)
-  system(*args) || abort("\n== Command #{args} failed ==")
-end
+STEPS=6
 
-chdir APP_ROOT do
-  # This script is a starting point to setup your application.
-  # Add necessary setup steps to this file.
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+NO_COLOR='\033[0m'
+CLEAR_LINE='\r\033[K'
 
-  puts '== Installing dependencies =='
-  system! 'gem install bundler --conservative'
-  system('bundle check') || system!('bundle install')
+# STEP 1
+printf "[1/${STEPS}]  checking dependencies"
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?('config/database.yml')
-  #   cp 'config/database.yml.sample', 'config/database.yml'
-  # end
+if ! command -v bundler > /dev/null; then
+  printf "${CLEAR_LINE}${RED}  You must install bundler before setup can continue${NO_COLOR}\n"
+  printf "    You should:\n"
+  printf "      $ gem install bundler\n"
+  exit -1
+fi
 
-  puts "\n== Preparing database =="
-  system! 'bin/rails db:setup'
+if ! command -v yarn > /dev/null; then
+  printf "${CLEAR_LINE}${RED}  You must install yarn before setup can continue${NO_COLOR}\n"
+  printf "    You should:\n"
+  printf "      $ brew install yarn\n"
+  exit -1
+fi
 
-  puts "\n== Removing old logs and tempfiles =="
-  system! 'bin/rails log:clear tmp:clear'
+if ! command -v copy_env > /dev/null; then
+  printf "${CLEAR_LINE}${RED}  You must install copy_env before setup can continue${NO_COLOR}\n"
+  printf "    You should:\n"
+  printf "      $ brew tap artsy/formulas\n"
+  printf "      $ brew install copy_env\n"
+  exit -1
+fi
 
-  puts "\n== Restarting application server =="
-  system! 'bin/rails restart'
-end
+# STEP 2
+printf "${CLEAR_LINE}[2/${STEPS}]  installing gems"
+bundle install > /dev/null
+
+# STEP 3
+printf "${CLEAR_LINE}[3/${STEPS}]  installing packages"
+yarn install > /dev/null
+
+# STEP 4
+printf "${CLEAR_LINE}[4/${STEPS}]  adding remotes"
+git remote add upstream git@github.com:artsy/rosalind.git
+git remote add staging git@heroku.com:rosalind-staging.git
+
+# STEP 5
+printf "${CLEAR_LINE}[5/${STEPS}]  fetching remotes"
+git fetch --all --quiet > /dev/null
+
+# STEP 6
+printf "${CLEAR_LINE}[6/${STEPS}]  setting up dotenv"
+copy_env
+
+# FINISH
+printf "${CLEAR_LINE}[6/${STEPS}]${GREEN}  finished!${NO_COLOR}\n"
